# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C65yyjtG7wwnZlzbifHRk1E2t8YQ5KBo
"""

import pandas as pd
baza={
  "FIsh":["Rahmatov Husniddin", "Murodov Torabek ","Zokirov Hurshud","Qadamova Zulayho","Abdullayeva Mohigul","Mamurova Mavluda ","Yusupov Dilyorbek"],
  "Yoshi":['20', '45', '30', '28', '29', '32', '26' ],
  "Manzili":[ 'Bshariq', 'Fargona','Andijon','Namangan','Toshkent','Qoqon','Sirdaryo' ],
  "jinsi":['erkak','erkak','erkak','ayol','ayol','ayol','erkak'],
  "Ish joyi":['JQB','Maktab','JQB','TATUFF','TATUFF','FARDU','FARDU']
}
db=pd.DataFrame(baza)
print(db)
filtr=db[db['jinsi']=='erkak']
print(filtr)
filtr=db[db['jinsi']=='ayol']
print(filtr)
filtr=db[(db['Ish joyi']=='JQB') & (db['Manzili']=='Andijon')]
print(filtr)
filtr=db[db['Yoshi']<'32']
print(filtr)